frontend:
  image: "nginx:latest" # Overridden by CLI
  replicas: 1

backend:
  image: "python:latest" # Overridden by CLI
  replicas: 1

ingress:
  host: "Lab-commit-task.commit.local"
  certificateArn: "" # Overridden by CLI