frontend:
  image: "lab-frontend:18-alpine" # Overridden by CLI
  replicas: 1
  version: "1.0.0"

backend:
  image: "lab-backend:3.11-slim" # Overridden by CLI
  replicas: 1

ingress:
  host: "lab-commit-task.commit.local"
  certificateArn: "" # Overridden by CLI